version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: nestjs_postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5430:5432"

volumes:
  pgdata:
